# .github/configs/label-commenter-config.yml

labels:
  - name: '审核中'
    labeled:
      issue:
        body: |
          **感谢您的支持，接下来请完成任务或等待审核！**
          
          您已经完成了友链申请，由于博主设置了友链申请条件，接下来博主将会等待条件满足后完成审批。

          > 如果您还未满足互换友链的条件，可以先去 [博客](https://xaoxuu.com) 里互动互动～
          
  - name: '审核中'
    unlabeled:
      issue:
        body: |
          **🎉 恭喜，友链添加成功！**

          稍后片刻刷新 [网页](https://xaoxuu.com/friends/) 就可以看到您的链接。

          > 如果您的站点信息发生了变动，请直接修改这个 issue 的内容。
  
  - name: '缺少互动'
    labeled:
      issue:
        body: |
          **🥹 很遗憾，部分条件未满足～**

          很感谢您的支持，但目前尚未满足交换友链的必要条件：与 xaoxuu 有至少**半年**的双向有效互动。
  
  - name: '缺少文章'
    labeled:
      issue:
        body: |
          **🥹 很遗憾，部分条件未满足～**

          很感谢您的支持，但尚未满足交换友链的必要条件：发布过至少 5 篇原创文章。

  - name: '未添加友链'
    labeled:
      issue:
        body: |
          **👋 请及时添加本站友链**

          距离成功只剩一步之遥了，请把本站添加到您的友链中，然后再下方评论告知。

  - name: '长期失联'
    labeled:
      issue:
        action: close
        body: |
          **⚠️ 抱歉，您的网站长期打不开，现已暂时下架。**

          如果您确认可以打开，请在下方评论告知，我们会在人工审核通过后恢复上架。
